# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'JLLogEncoding' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for JLLogEncoding
  pod 'AFNetworking', '~> 3.1.0'



  target 'JLLogEncodingTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'JLLogEncodingUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
